name: GenderEx Run
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  genderex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"

      - name: Install GenderEx
        run: pip install https://github.com/Theta-Dev/Spotify-Gender-Ex/archive/refs/heads/master.zip
      
      - uses: actions/checkout@v2
      
      - name: Run GenderEx
        run: spotify-gender-ex --noia --kspw '${{ secrets.KEYSTORE_PASSWORD }}' --kypw '${{ secrets.KEY_PASSWORD }}' --gh-token ${{ secrets.MY_GH_TOKEN }}
      
      - name: Upload to MEGA.nz
        if: hashFiles(env.apk_file) != ''
        run: |
          curl https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megacmd_1.4.0-5.1_amd64.deb --output megacmd.deb
          sudo apt-get install ./megacmd.deb -y
          mega-login ${{ secrets.MEGA_USER }} ${{ secrets.MEGA_PASS }}
          mega-put ${{ env.apk_file }} /Spotify-GenderEx/
      
      - name: Save latest Spotify version
        if: hashFiles(env.apk_file) != ''
        uses: EndBug/add-and-commit@v7
        with:
          add: 'GenderEx/spotify_version.txt'
          default_author: github_actions
          message: 'Updated spotify version to ${{ env.spotify_version }}'
      
      - name: Create message
        if: hashFiles(env.apk_file) != ''
        run: |
          echo 'Spotify *${{ env.spotify_version }}* wurde erfolgreich degenderifiziert!' > msg.txt
          echo 'Spotify-Gender-Ex: `${{ env.genderex_version }}`' >> msg.txt
          echo 'Ersetzungstabellen: `${{ env.rt_versions }}`' >> msg.txt
          echo 'Neue Ersetzungsregeln: `${{ env.repl_string }}`' >> msg.txt
      
      - name: Notify via Telegram
        if: hashFiles(env.apk_file) != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message_file: msg.txt
          format: markdown
