name: GenderEx Live
on: workflow_dispatch
jobs:
  genderex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"

      - name: Install GenderEx
        run: pip install --extra-index-url https://test.pypi.org/simple/ Spotify-Gender-Ex==3.0.0
      
      - uses: actions/checkout@v2
      
      - name: Run GenderEx
        run: spotify-gender-ex --noia --kspw '${{ secrets.KEYSTORE_PASSWORD }}' --kypw '${{ secrets.KEY_PASSWORD }}' --gh-token ${{ secrets.MY_GH_TOKEN }}
      
      - name: Upload to MEGA.nz
        if: ${{ env.apk_file }} != ''
        uses: Difegue/action-megacmd@master
        with:
          args: put ${{ env.apk_file }} /Spotify-GenderEx/
        env:
          USERNAME: ${{ secrets.MEGA_USER }}
          PASSWORD: ${{ secrets.MEGA_PASS }}
      
      - name: Save latest Spotify version
        if: ${{ env.apk_file }} != ''
        uses: EndBug/add-and-commit@v7
        with:
          add: 'GenderEx/spotify_version.txt'
          pull_strategy: '--rebase'
          default_author: github_actions
          message: 'Updated spotify version to ${{ env.spotify_version }}'
      
      - name: Notify via Telegram
        if: ${{ env.apk_file }} != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 'Spotify ${{ env.spotify_version }} wurde erfolgreich degenderifiziert.\n\n${{ env.apk_file }}'
